# Generated by Django 5.2.1 on 2025-08-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='texto_para_copiar',
            field=models.TextField(blank=True, help_text='Texto formateado con todos los datos del ítem', null=True),
        ),
    ]
