# Generated by Django 5.2.1 on 2025-08-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontiempos',
            name='tiempo_fotografia',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='configuraciontiempos',
            name='tiempo_impresion',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='configuraciontiempos',
            name='tiempo_ingreso',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='configuraciontiempos',
            name='tiempo_revision',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en segundos', null=True),
        ),
    ]
